export {
  isInView,
  createInViewChecker,
  scrollManager,
  onIntersect,
  getElement,
  getElements,
  addClass,
  addEvent,
  on,
  delegate,
  removeClass,
  toggleClass,
  setStyle,
  getStyle,
  setHtml,
  setText,
  IsInViewOptions,
  ScrollData,
  ScrollSubscribeOptions,
  OneTimeTriggerOptions,
  ScrollManagerInstance,
} from './index';
